import { defineField, defineType } from "sanity";
import { CogIcon } from "@sanity/icons";

/* Singleton (_id: "siteSettings") — business facts (single source for the
   footer, contact section and LocalBusiness JSON-LD), navigation labels and
   UI microcopy. */
export const siteSettingsType = defineType({
  name: "siteSettings",
  title: "Site-instellingen",
  type: "document",
  icon: CogIcon,
  groups: [
    { name: "business", title: "Bedrijf", default: true },
    { name: "nav", title: "Navigatie" },
    { name: "contactSection", title: "Contact-sectie" },
    { name: "footer", title: "Footer" },
    { name: "ui", title: "Interface" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "business",
      title: "Bedrijfsgegevens",
      type: "object",
      group: "business",
      description: "Feiten over de zaak — gebruikt in footer, contact en lokale SEO (LocalBusiness).",
      fieldsets: [
        { name: "address", title: "Adres", options: { collapsible: true, collapsed: true } },
        { name: "contact", title: "Contact", options: { collapsible: true, collapsed: true } },
        { name: "legal", title: "Administratief", options: { collapsible: true, collapsed: true } },
        { name: "localSeo", title: "Lokale SEO", options: { collapsible: true, collapsed: true } },
      ],
      fields: [
        defineField({ name: "siteName", title: "Naam", type: "string", validation: (r) => r.required() }),
        defineField({
          name: "jobTitle",
          title: "Beroep",
          description: "Per taal, b.v. “Analoog fotograaf — Antwerpen & Brussel”.",
          type: "internationalizedArrayString",
        }),
        defineField({ name: "streetAddress", title: "Straat + nummer", type: "string", fieldset: "address" }),
        defineField({ name: "postalCode", title: "Postcode", type: "string", fieldset: "address" }),
        defineField({ name: "city", title: "Gemeente", type: "string", fieldset: "address" }),
        defineField({ name: "countryCode", title: "Landcode", type: "string", initialValue: "BE", fieldset: "address" }),
        defineField({
          name: "phone",
          fieldset: "contact",
          title: "Telefoon (internationaal, zonder spaties)",
          description: "Gebruikt voor tel:-links en structured data, b.v. +32476506209.",
          type: "string",
        }),
        defineField({ name: "phoneDisplay", title: "Telefoon (weergave)", type: "string", fieldset: "contact" }),
        defineField({ name: "email", title: "E-mail", type: "string", validation: (r) => r.email(), fieldset: "contact" }),
        defineField({ name: "instagramUrl", title: "Instagram URL", type: "url", fieldset: "contact" }),
        defineField({ name: "instagramHandle", title: "Instagram handle", type: "string", fieldset: "contact" }),
        defineField({ name: "vatNumber", title: "BTW-nummer", type: "string", fieldset: "legal" }),
        defineField({ name: "bankName", title: "Bank", type: "string", fieldset: "legal" }),
        defineField({ name: "iban", title: "IBAN", type: "string", fieldset: "legal" }),
        defineField({
          name: "areaServed",
          fieldset: "localSeo",
          title: "Werkgebied",
          description: "Steden/regio's voor lokale SEO, b.v. Antwerpen, Brussel.",
          type: "array",
          of: [{ type: "string" }],
        }),
        defineField({
          name: "geo",
          fieldset: "localSeo",
          title: "Locatie (atelier)",
          description: "Coördinaten van het atelier voor lokale SEO.",
          type: "geopoint",
        }),
        defineField({
          name: "priceRange",
          fieldset: "localSeo",
          title: "Prijsklasse",
          description: "Optioneel, b.v. “€€€” — gebruikt in structured data.",
          type: "string",
        }),
      ],
    }),
    defineField({
      name: "nav",
      title: "Navigatielabels",
      type: "object",
      group: "nav",
      fields: [
        defineField({ name: "filosofie", title: "Filosofie", type: "internationalizedArrayString" }),
        defineField({ name: "uitvaart", title: "Uitvaart", type: "internationalizedArrayString" }),
        defineField({ name: "portret", title: "Portret", type: "internationalizedArrayString" }),
        defineField({ name: "huwelijk", title: "Huwelijk", type: "internationalizedArrayString" }),
        defineField({ name: "werk", title: "Werk", type: "internationalizedArrayString" }),
        defineField({ name: "contact", title: "Contact", type: "internationalizedArrayString" }),
      ],
    }),
    defineField({
      name: "contactSection",
      title: "Contact-sectie",
      type: "object",
      group: "contactSection",
      description: "De contact-sectie op de landingspagina en dienstpagina's. Waarden (nummer, adres…) komen uit Bedrijfsgegevens.",
      fields: [
        defineField({ name: "overline", title: "Overline", type: "internationalizedArrayString" }),
        defineField({ name: "title", title: "Titel", type: "internationalizedArrayString" }),
        defineField({ name: "body", title: "Tekst", type: "internationalizedArrayText" }),
        defineField({ name: "callBtn", title: "Bel-knop", type: "internationalizedArrayString" }),
        defineField({ name: "mailBtn", title: "Mail-knop", type: "internationalizedArrayString" }),
        defineField({ name: "phoneLabel", title: "Label: telefoon", type: "internationalizedArrayString" }),
        defineField({ name: "emailLabel", title: "Label: e-mail", type: "internationalizedArrayString" }),
        defineField({ name: "studioLabel", title: "Label: atelier", type: "internationalizedArrayString" }),
        defineField({ name: "instagramLabel", title: "Label: Instagram", type: "internationalizedArrayString" }),
      ],
    }),
    defineField({
      name: "footer",
      title: "Footer",
      type: "object",
      group: "footer",
      fields: [
        defineField({ name: "tagline", title: "Tagline", type: "internationalizedArrayString" }),
        defineField({ name: "navTitle", title: "Kolomtitel: pagina", type: "internationalizedArrayString" }),
        defineField({ name: "contactTitle", title: "Kolomtitel: contact", type: "internationalizedArrayString" }),
        defineField({ name: "legalTitle", title: "Kolomtitel: administratief", type: "internationalizedArrayString" }),
        defineField({
          name: "vatLabel",
          title: "BTW-label",
          description: "“BTW” / “VAT” / “TVA” — vóór het BTW-nummer.",
          type: "internationalizedArrayString",
        }),
        defineField({ name: "rights", title: "Copyright-regel", type: "internationalizedArrayString" }),
        defineField({ name: "made", title: "Slotregel", type: "internationalizedArrayString" }),
      ],
    }),
    defineField({
      name: "ui",
      title: "Interface-teksten",
      type: "object",
      group: "ui",
      fieldsets: [
        { name: "rails", title: "Rails", options: { collapsible: true, collapsed: true } },
        { name: "showcase", title: "Showcase & algemeen", options: { collapsible: true, collapsed: true } },
        { name: "sectionLabels", title: "Sectielabels (dienstpagina)", options: { collapsible: true, collapsed: true } },
        { name: "gallery", title: "Galerij", options: { collapsible: true, collapsed: true } },
        { name: "formules", title: "Formules & andere diensten", options: { collapsible: true, collapsed: true } },
      ],
      fields: [
        defineField({ name: "railWork", title: "Rail: werk", type: "internationalizedArrayString", fieldset: "rails" }),
        defineField({ name: "railServices", title: "Rail: diensten", type: "internationalizedArrayString", fieldset: "rails" }),
        defineField({ name: "railProcess", title: "Rail: traject", type: "internationalizedArrayString", fieldset: "rails" }),
        defineField({ name: "showcaseHeading", title: "Showcase-kop", type: "internationalizedArrayString", fieldset: "showcase" }),
        defineField({ name: "serviceCta", title: "Dienst-CTA", type: "internationalizedArrayString", fieldset: "showcase" }),
        defineField({ name: "themeLabel", title: "Thema-toggle label", type: "internationalizedArrayString", fieldset: "showcase" }),
        defineField({ name: "spBack", title: "Dienstpagina: terug-link", type: "internationalizedArrayString", fieldset: "showcase" }),
        defineField({ name: "navWhy", title: "Sectielabel: waarom", type: "internationalizedArrayString", fieldset: "sectionLabels" }),
        defineField({ name: "navHow", title: "Sectielabel: werkwijze", type: "internationalizedArrayString", fieldset: "sectionLabels" }),
        defineField({ name: "navPiece", title: "Sectielabel: het stuk", type: "internationalizedArrayString", fieldset: "sectionLabels" }),
        defineField({ name: "navPackages", title: "Sectielabel: formules", type: "internationalizedArrayString", fieldset: "sectionLabels" }),
        defineField({ name: "navFaq", title: "Sectielabel: vragen", type: "internationalizedArrayString", fieldset: "sectionLabels" }),
        defineField({ name: "spGalleryOverline", title: "Galerij: overline", type: "internationalizedArrayString", fieldset: "gallery" }),
        defineField({ name: "spGalleryTitle", title: "Galerij: titel", type: "internationalizedArrayString", fieldset: "gallery" }),
        defineField({ name: "spGalleryNote", title: "Galerij: nota", type: "internationalizedArrayText", fieldset: "gallery" }),
        defineField({ name: "spCross", title: "Andere diensten: kop", type: "internationalizedArrayString", fieldset: "formules" }),
        defineField({ name: "spPopular", title: "Formule-badge", type: "internationalizedArrayString", fieldset: "formules" }),
        defineField({ name: "spAsk", title: "Formule-CTA", type: "internationalizedArrayString", fieldset: "formules" }),
      ],
    }),
    defineField({
      name: "seo",
      title: "Standaard-SEO",
      description: "Fallback voor pagina's zonder eigen SEO-velden.",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    prepare() {
      return { title: "Site-instellingen" };
    },
  },
});
